#pragma once

#include "peripherals/CLOCKS.hpp"
#include "peripherals/I2C.hpp"
#include "peripherals/IO_QSPI.hpp"
#include "peripherals/IO_BANK0.hpp"
#include "peripherals/PIO.hpp"
#include "peripherals/PLL.hpp"
#include "peripherals/PSM.hpp"
#include "peripherals/PWM.hpp"
#include "peripherals/RESETS.hpp"
#include "peripherals/SPI.hpp"
#include "peripherals/UART.hpp"
#include "peripherals/USBCTRL_DPRAM.hpp"
#include "peripherals/USBCTRL_REGS.hpp"
#include "peripherals/WATCHDOG.hpp"
#include "peripherals/XIP_SSI.hpp"
#include "peripherals/XOSC.hpp"

///
#include "CRC.hpp"
#include "DMA.hpp"
#include "I2C.hpp"
#include "Interrupt.hpp"
#include "Io.hpp"
#include "PIO.hpp"
#include "SPI.hpp"
#include "Serial_Number.hpp"
#include "StartUp.hpp"
#include "UART.hpp"
#include "chip_reset.hpp"
#include "clock_config.hpp"
#include "core/core.hpp"
#include "flash.hpp"
#include "pwm.hpp"
#include "rom_functions.hpp"
#include "usb.hpp"
#include "watchdog.hpp"
