FROM kvasirio/kvasir:latest AS rp2040_dev

ENV CHIP_ROOT=/opt/chip
COPY . ${CHIP_ROOT}/

# kvasir_devices: chip.hpp includes drivers from it, so cmake/chip.cmake needs it (next to the SDK, found by default).
ENV KVASIR_DEVICES_ROOT=/opt/kvasir_devices
RUN git clone https://github.com/kvasir-io/kvasir_devices.git ${KVASIR_DEVICES_ROOT} && \
    git config --global --add safe.directory ${KVASIR_DEVICES_ROOT}

RUN su aur_user -c "yay -S --noconfirm --disable-download-timeout --asdeps gcc-arm-none-eabi-bin && yay -S --noconfirm --disable-download-timeout --removemake picotool" && \
    rm -rf /home/aur_user/* rm -rf /home/aur_user/.* && \
    git config --global --add safe.directory ${CHIP_ROOT}

ENTRYPOINT ["/opt/kvasir/scripts/entrypoint.sh"]
